/**
 * AUTO-GENERATED by @workspace/scripts articles:build.
 * Do not hand-edit — regenerate with:
 *   pnpm --filter @workspace/scripts run articles:build
 *
 * Map of app.jesusonline.com slug → metadata for a locally hosted PDF at
 * /articles/<slug>.pdf. The channels page uses hasArticlePdf() to decide
 * whether to activate an item's PDF button.
 */

export interface ArticlePdfMeta {
  title: string;
  bytes: number;
  modified: string;
}

export const articlePdfs: Record<string, ArticlePdfMeta> = {
  "20010-experiencing-god-24-7": { title: "Experiencing God 24/7 Overview", bytes: 108659, modified: "2023-11-02T22:33:42" },
  "20011-quiet-time-with-god": { title: "Quiet Time with God", bytes: 115149, modified: "2023-11-07T19:42:04" },
  "20012-activity-time-with-god": { title: "Activity Time with God", bytes: 110857, modified: "2023-11-02T17:58:21" },
};

/** Extract the app-slug portion of an app.jesusonline.com/post/<slug> URL. */
export function extractAppSlug(url: string | undefined | null): string | undefined {
  if (!url) return undefined;
  const m = url.match(/app\.jesusonline\.com\/post\/([^/?#]+)/);
  return m?.[1];
}

export function hasArticlePdf(appSlug: string | undefined | null): boolean {
  return !!appSlug && appSlug in articlePdfs;
}

export function getArticlePdfMeta(appSlug: string): ArticlePdfMeta | undefined {
  return articlePdfs[appSlug];
}
