/**
 * AUTO-GENERATED by @workspace/scripts bcg:pdf.
 * Do not hand-edit — regenerate with:
 *   pnpm --filter @workspace/scripts run bcg:pdf
 *
 * Map of BCG article id → metadata for a locally hosted PDF at
 * /articles/bcg/<id>.pdf. The article page uses hasBcgArticlePdf() to decide
 * whether to show a "Download PDF" button.
 */

export interface BcgArticlePdfMeta {
  bytes: number;
}

export const bcgArticlePdfs: Record<string, BcgArticlePdfMeta> = {
  "a-great-commission-church": { bytes: 103343 },
  "a-hope-filled-church": { bytes: 102636 },
  "a-jesusonline-equipped-church": { bytes: 629944 },
  "a-love-demonstrating-relational-church": { bytes: 107766 },
  "a-spirit-dependent-church": { bytes: 89656 },
  "a-total-life-discipleship-church": { bytes: 585550 },
  "a-transformational-teaching-church": { bytes: 434762 },
  "an-attractive-and-inviting-church": { bytes: 114624 },
  "an-intentional-worship-church": { bytes: 112596 },
  "an-online-outreach-church": { bytes: 99279 },
  "anatomy-of-obedience": { bytes: 383037 },
  "gods-unique-vision-for-your-church": { bytes: 634697 },
};

export function hasBcgArticlePdf(id: string | undefined | null): boolean {
  return !!id && id in bcgArticlePdfs;
}

export function getBcgArticlePdfMeta(id: string): BcgArticlePdfMeta | undefined {
  return bcgArticlePdfs[id];
}
