/**
 * AUTO-GENERATED by @workspace/scripts bcg:pdf.
 * Do not hand-edit — regenerate with:
 *   pnpm --filter @workspace/scripts run bcg:pdf
 *
 * Map of BCG article id → metadata for a locally hosted PDF at
 * /articles/bcg/<id>.pdf. The article page uses hasBcgArticlePdf() to decide
 * whether to show a "Download PDF" button.
 */

export interface BcgArticlePdfMeta {
  bytes: number;
}

export const bcgArticlePdfs: Record<string, BcgArticlePdfMeta> = {
  "a-great-commission-church": { bytes: 507305 },
  "a-hope-filled-church": { bytes: 543164 },
  "a-jesusonline-equipped-church": { bytes: 647550 },
  "a-love-demonstrating-relational-church": { bytes: 597375 },
  "a-model-church": { bytes: 126272 },
  "a-spirit-dependent-church": { bytes: 533094 },
  "a-total-life-discipleship-church": { bytes: 693585 },
  "a-transformational-teaching-church": { bytes: 482939 },
  "aids-that-strengthen-lasting-retention": { bytes: 102029 },
  "an-attractive-and-inviting-church": { bytes: 199432 },
  "an-attractive-church": { bytes: 500188 },
  "an-intentional-worship-church": { bytes: 456729 },
  "an-inviting-church": { bytes: 503750 },
  "an-online-outreach-church": { bytes: 816865 },
  "anatomy-of-obedience": { bytes: 410448 },
  "give-them-what-they-need": { bytes: 117142 },
  "gods-unique-vision-for-your-church": { bytes: 643615 },
  "retention-leads-to-transformation": { bytes: 111422 },
  "what-is-your-motivation-for-preaching": { bytes: 110362 },
};

export function hasBcgArticlePdf(id: string | undefined | null): boolean {
  return !!id && id in bcgArticlePdfs;
}

export function getBcgArticlePdfMeta(id: string): BcgArticlePdfMeta | undefined {
  return bcgArticlePdfs[id];
}
