/**
 * AUTO-GENERATED by @workspace/scripts bsm:pdf.
 * Do not hand-edit — regenerate with:
 *   pnpm --filter @workspace/scripts run bsm:pdf
 *
 * Map of Bible Study Method article id → metadata for a locally hosted PDF at
 * /articles/bsm/<id>.pdf. The article page uses hasBsmArticlePdf() to decide
 * whether to show a "Download PDF" button.
 */

export interface BsmArticlePdfMeta {
  bytes: number;
}

export const bsmArticlePdfs: Record<string, BsmArticlePdfMeta> = {
  "bible-recap": { bytes: 132833 },
  "essential-bible-study-tools": { bytes: 165359 },
  "inductive-bible-study": { bytes: 128331 },
  "soap-method": { bytes: 123130 },
  "topical-bible-study": { bytes: 127883 },
};

export function hasBsmArticlePdf(id: string | undefined | null): boolean {
  return !!id && id in bsmArticlePdfs;
}

export function getBsmArticlePdfMeta(id: string): BsmArticlePdfMeta | undefined {
  return bsmArticlePdfs[id];
}
