/**
 * Loader for generated site-wide on-EQUIP articles (all channels except
 * Evidence, which has its own evidenceArticles.ts).
 *
 * Data lives in src/data/generated/articles/<subId>.json, one file per
 * sub-topic, AUTO-GENERATED by @workspace/scripts site-articles:build.
 * Never hand-edit those files.
 *
 * Article ids are only unique within a sub-topic (some courses share content
 * across channels), so lookups are keyed by (subId, articleId).
 */

import type { ArticleBlock } from "./bcgArticles";

export interface SiteArticle {
  id: string;
  /** Source app.jesusonline.com post slug (keys articles.ts PDF manifest). */
  appSlug?: string;
  /** Owning sub-topic id. */
  subId: string;
  /** Owning channel id. */
  channelId: string;
  title: string;
  description: string;
  /** Embeddable YouTube URL (youtube-nocookie) when the source post has a video. */
  videoUrl?: string;
  /** Explicit site-relative PDF path for locally maintained articles. */
  pdf?: string;
  /** True when this article is maintained in the local overlay. */
  localSource?: boolean;
  /** Main overview article that owns this supporting detail article. */
  parentArticleId?: string;
  blocks: ArticleBlock[];
}

const generatedModules = import.meta.glob<{ default: SiteArticle[] }>("./generated/articles/*.json", {
  eager: true,
});
const localModules = import.meta.glob<{ default: SiteArticle[] }>("./local/articles/*.json", {
  eager: true,
});

const generatedArticles = Object.keys(generatedModules)
  .sort()
  .flatMap(k => generatedModules[k].default);
const localArticles = Object.keys(localModules)
  .sort()
  .flatMap(k => localModules[k].default);

/* Local manuscripts are an intentional, persistent overlay on the generated
   catalog. Merge them last so an upstream rebuild (including --force) cannot
   displace locally owned content, while retaining declaration order. */
const merged = new Map<string, SiteArticle>();
for (const article of generatedArticles) {
  merged.set(`${article.subId}/${article.id}`, article);
}
for (const article of localArticles) {
  merged.set(`${article.subId}/${article.id}`, article);
}

export const siteArticles: SiteArticle[] = [...merged.values()];

const byKey = new Map(siteArticles.map(a => [`${a.subId}/${a.id}`, a]));

export function getSiteArticle(subId: string, id: string): SiteArticle | undefined {
  return byKey.get(`${subId}/${id}`);
}

export function hasSiteArticle(subId: string, id: string): boolean {
  return byKey.has(`${subId}/${id}`);
}

/** Next article within the same sub-topic (declaration order, no wrap). */
export function getNextSiteArticle(subId: string, id: string): SiteArticle | undefined {
  const siblings = siteArticles.filter(a => a.subId === subId);
  const idx = siblings.findIndex(a => a.id === id);
  return idx >= 0 && idx + 1 < siblings.length ? siblings[idx + 1] : undefined;
}
