/**
 * Loader for generated site-wide on-EQUIP articles (all channels except
 * Evidence, which has its own evidenceArticles.ts).
 *
 * Data lives in src/data/generated/articles/<subId>.json, one file per
 * sub-topic, AUTO-GENERATED by @workspace/scripts site-articles:build.
 * Never hand-edit those files.
 *
 * Article ids are only unique within a sub-topic (some courses share content
 * across channels), so lookups are keyed by (subId, articleId).
 */

import type { ArticleBlock } from "./bcgArticles";

export interface SiteArticle {
  id: string;
  /** Source app.jesusonline.com post slug (keys articles.ts PDF manifest). */
  appSlug: string;
  /** Owning sub-topic id. */
  subId: string;
  /** Owning channel id. */
  channelId: string;
  title: string;
  description: string;
  blocks: ArticleBlock[];
}

const modules = import.meta.glob<{ default: SiteArticle[] }>("./generated/articles/*.json", {
  eager: true,
});

export const siteArticles: SiteArticle[] = Object.keys(modules)
  .sort()
  .flatMap(k => modules[k].default);

const byKey = new Map(siteArticles.map(a => [`${a.subId}/${a.id}`, a]));

export function getSiteArticle(subId: string, id: string): SiteArticle | undefined {
  return byKey.get(`${subId}/${id}`);
}

export function hasSiteArticle(subId: string, id: string): boolean {
  return byKey.has(`${subId}/${id}`);
}

/** Next article within the same sub-topic (declaration order, no wrap). */
export function getNextSiteArticle(subId: string, id: string): SiteArticle | undefined {
  const siblings = siteArticles.filter(a => a.subId === subId);
  const idx = siblings.findIndex(a => a.id === id);
  return idx >= 0 && idx + 1 < siblings.length ? siblings[idx + 1] : undefined;
}
